import type { Metadata } from "next";
// import localFont from "next/font/local";
import { ThemeProvider } from "@/components/theme-provider";

import "../globals.css";

import { Toaster } from "@/components/ui/toaster";

// const AntonSC = localFont({
//   src: "../fonts/SCHABO-Condensed.woff",
//   variable: "--font-antonsc",
//   weight: "100 900",
// });

// const RobotoCondensed = localFont({
//   src: "../fonts/RobotoCondensed-VariableFont_wght.ttf",
//   variable: "--font-robotorondensed",
//   weight: "100 900",
// });
// const geistSans = localFont({
//   src: "../fonts/GeistMonoVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`bg-cover bg-no-repeat   relative antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
// ${geistSans.variable} ${geistMono.variable} ${AntonSC.variable} ${RobotoCondensed.variable}
